name: Pull Request Labeler

on:
  pull_request:
    types:
      - opened

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
      - name: Add a label when a PR is opened
        uses: actions/labeler@v3-preview
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
